# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_author.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='notes', max_length=255),
        ),
    ]
